export const _candidates = [
  {
    cv_id: 'cv-001',
    candidate_id: 'cand-001',
    cv_metadata: {
      cv_text: 'Experienced software engineer with expertise in web development.',
      cv_language: 'en',
      summary: '5+ years in full-stack development using React and Node.js.',
    },
    candidate: {
      full_name: 'Alice Johnson',
      first_name: 'Alice',
      last_name: 'Johnson',
      email: 'alice.johnson@example.com',
      phone: '+1234567890',
      birth_date: '1991-06-10',
      address: '789 Pine Street, Seattle, WA',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Web Development',
      experience_years: 6,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/alicejohnson',
      },
      {
        platform: 'Twitter',
        url: 'https://twitter.com/alice_dev',
      },
    ],
    education: [
      {
        degree: 'BSc Computer Engineering',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Computer Engineering',
        institution: 'University of Washington',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2013',
      },
    ],
    experience: [
      {
        company_name: 'Tech Innovators',
        industry: 'Software',
        country: 'US',
        job_title: 'Full-Stack Developer',
        start_date: '2018-04-01',
        end_date: '9999-12-31',
        description: 'Led the front-end development of scalable web applications.',
      },
    ],
    skills: [
      { name: 'React', category: 'Frontend' },
      { name: 'Node.js', category: 'Backend' },
    ],
    keywords: [{ keyword: 'Web App', relevance_score: 0.85 }],
    certifications: [{ name: 'Google Cloud Developer', provider: 'Google', year: '2021' }],
    projects: [
      {
        title: 'E-commerce Platform',
        description: 'Built a multi-vendor e-commerce app.',
        role: 'Lead Developer',
        technologies_used: ['React', 'Node.js', 'MongoDB'],
        start_date: '2022-01-01',
        end_date: '2022-12-31',
        project_url: 'https://github.com/alice/ecommerce-platform',
        impact: 'Handled 10k+ users monthly.',
        client_or_employer: 'RetailTech',
      },
    ],
    processing_details: {
      processing_time_sec: 1.2,
      source_file: 'alice_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-03-13T12:00:00Z',
      cv_hash: 'hash-alice-001',
    },
  },

  {
    cv_id: 'cv-002',
    candidate_id: 'cand-002',
    cv_metadata: {
      cv_text: 'Data Scientist skilled in ML and Python.',
      cv_language: 'en',
      summary: 'Data scientist with strong background in machine learning and statistics.',
    },
    candidate: {
      full_name: 'Bob Smith',
      first_name: 'Bob',
      last_name: 'Smith',
      email: 'bob.smith@example.com',
      phone: '+1987654321',
      birth_date: '1988-11-23',
      address: '456 Oak Avenue, Austin, TX',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Data Science',
      experience_years: 8,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/bsmith',
      },
      {
        platform: 'Facebook',
        url: 'https://www.facebook.com/bob.smith.ds',
      },
    ],
    education: [
      {
        degree: 'MSc Data Science',
        degree_Level: 'ISCED 7',
        degree_type: 'Master',
        field_of_study: 'Data Science',
        institution: 'UT Austin',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2016',
      },
    ],
    experience: [
      {
        company_name: 'AI Solutions',
        industry: 'Artificial Intelligence',
        country: 'US',
        job_title: 'Data Scientist',
        start_date: '2017-05-01',
        end_date: '9999-12-31',
        description: 'Designed machine learning models for fraud detection.',
      },
    ],
    skills: [
      { name: 'Python', category: 'Programming' },
      { name: 'Scikit-learn', category: 'Machine Learning' },
    ],
    keywords: [{ keyword: 'Fraud Detection', relevance_score: 0.95 }],
    certifications: [
      { name: 'TensorFlow Developer Certificate', provider: 'Google', year: '2020' },
    ],
    projects: [
      {
        title: 'Fraud Detection System',
        description: 'Built a real-time fraud detection model.',
        role: 'ML Engineer',
        technologies_used: ['Python', 'TensorFlow', 'Kafka'],
        start_date: '2021-01-01',
        end_date: '2021-12-01',
        project_url: '',
        impact: 'Reduced fraud by 40%.',
        client_or_employer: 'FinSecure Inc.',
      },
    ],
    processing_details: {
      processing_time_sec: 0.9,
      source_file: 'bob_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-03-10T15:30:00Z',
      cv_hash: 'hash-bob-002',
    },
  },

  {
    cv_id: 'cv-003',
    candidate_id: 'cand-003',
    cv_metadata: {
      cv_text: 'UI/UX designer focused on user-centered design.',
      cv_language: 'en',
      summary: 'Creative designer with 7 years of UI/UX experience.',
    },
    candidate: {
      full_name: 'Carla Mendes',
      first_name: 'Carla',
      last_name: 'Mendes',
      email: 'carla.m@example.com',
      phone: '+351987654321',
      birth_date: '1992-03-19',
      address: 'Rua Lisboa, Portugal',
      country_code: 'PT',
      country_name: 'Portugal',
      industry: 'Design',
      experience_years: 7,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://linkedin.com/in/carla-mendes',
      },
    ],
    education: [
      {
        degree: 'Bachelor in Graphic Design',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Design',
        institution: 'University of Porto',
        institution_type: 'University',
        country: 'PT',
        education_framework: 'ISCED',
        graduation_year: '2014',
      },
    ],
    experience: [
      {
        company_name: 'Creative Labs',
        industry: 'Design',
        country: 'PT',
        job_title: 'UX Designer',
        start_date: '2016-09-01',
        end_date: '9999-12-31',
        description: 'Redesigned mobile apps for optimal UX.',
      },
    ],
    skills: [
      { name: 'Figma', category: 'Design Tools' },
      { name: 'Adobe XD', category: 'Design Tools' },
    ],
    keywords: [{ keyword: 'User Experience', relevance_score: 0.88 }],
    certifications: [{ name: 'UX Certified', provider: 'NN/g', year: '2019' }],
    projects: [
      {
        title: 'Mobile Banking UX',
        description: 'Improved onboarding for a banking app.',
        role: 'UX Lead',
        technologies_used: ['Figma', 'Sketch'],
        start_date: '2022-06-01',
        end_date: '2023-06-01',
        project_url: '',
        impact: 'Increased user retention by 30%.',
        client_or_employer: 'FinBank',
      },
    ],
    processing_details: {
      processing_time_sec: 1.1,
      source_file: 'carla_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-03-01T11:00:00Z',
      cv_hash: 'hash-carla-003',
    },
  },

  {
    cv_id: 'cv-004',
    candidate_id: 'cand-004',
    cv_metadata: {
      cv_text: 'DevOps engineer with cloud automation expertise.',
      cv_language: 'en',
      summary: 'DevOps engineer with deep experience in CI/CD and AWS.',
    },
    candidate: {
      full_name: 'Daniel Zhang',
      first_name: 'Daniel',
      last_name: 'Zhang',
      email: 'daniel.z@example.com',
      phone: '+8613800138000',
      birth_date: '1985-08-12',
      address: 'Shenzhen, Guangdong, China',
      country_code: 'CN',
      country_name: 'China',
      industry: 'Cloud Engineering',
      experience_years: 10,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://linkedin.com/in/dzhang',
      },
    ],
    education: [
      {
        degree: 'Bachelor in Computer Science',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Computer Science',
        institution: 'Tsinghua University',
        institution_type: 'University',
        country: 'CN',
        education_framework: 'ISCED',
        graduation_year: '2007',
      },
    ],
    experience: [
      {
        company_name: 'CloudOps Ltd.',
        industry: 'Cloud',
        country: 'CN',
        job_title: 'DevOps Engineer',
        start_date: '2015-01-01',
        end_date: '9999-12-31',
        description: 'Automated deployments and infrastructure using Terraform and Ansible.',
      },
    ],
    skills: [
      { name: 'AWS', category: 'Cloud' },
      { name: 'Terraform', category: 'DevOps' },
    ],
    keywords: [{ keyword: 'Infrastructure as Code', relevance_score: 0.92 }],
    certifications: [{ name: 'AWS DevOps Pro', provider: 'Amazon Web Services', year: '2022' }],
    projects: [
      {
        title: 'CI/CD Platform',
        description: 'Built a self-service CI/CD platform for internal teams.',
        role: 'DevOps Lead',
        technologies_used: ['Jenkins', 'Docker', 'AWS'],
        start_date: '2020-01-01',
        end_date: '2021-12-31',
        project_url: '',
        impact: 'Cut release times by 70%.',
        client_or_employer: 'CloudOps Ltd.',
      },
    ],
    processing_details: {
      processing_time_sec: 1.3,
      source_file: 'daniel_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-03-05T14:00:00Z',
      cv_hash: 'hash-daniel-004',
    },
  },
  {
    cv_id: 'cv-005',
    candidate_id: 'cand-005',
    cv_metadata: {
      cv_text: 'Mobile App Developer with expertise in Flutter and Kotlin.',
      cv_language: 'en',
      summary: '5+ years in mobile development, specializing in cross-platform solutions.',
    },
    candidate: {
      full_name: 'Eva Carter',
      first_name: 'Eva',
      last_name: 'Carter',
      email: 'eva.carter@example.com',
      phone: '+447876543210',
      birth_date: '1990-04-22',
      address: '123 Elm Street, London, UK',
      country_code: 'GB',
      country_name: 'United Kingdom',
      industry: 'Mobile Development',
      experience_years: 5,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/evacarter',
      },
    ],
    education: [
      {
        degree: 'BSc Software Engineering',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Software Engineering',
        institution: 'University of London',
        institution_type: 'University',
        country: 'GB',
        education_framework: 'ISCED',
        graduation_year: '2015',
      },
    ],
    experience: [
      {
        company_name: 'MobileTech Solutions',
        industry: 'Technology',
        country: 'GB',
        job_title: 'Mobile App Developer',
        start_date: '2017-06-01',
        end_date: '9999-12-31',
        description: 'Developed cross-platform apps using Flutter and Kotlin.',
      },
    ],
    skills: [
      { name: 'Flutter', category: 'Mobile' },
      { name: 'Kotlin', category: 'Mobile' },
    ],
    keywords: [{ keyword: 'Cross-Platform', relevance_score: 0.91 }],
    certifications: [{ name: 'Flutter Developer', provider: 'Google', year: '2019' }],
    projects: [
      {
        title: 'Fitness Tracker App',
        description: 'Developed a cross-platform fitness tracking app.',
        role: 'Lead Developer',
        technologies_used: ['Flutter', 'Firebase'],
        start_date: '2020-02-01',
        end_date: '2020-12-01',
        project_url: '',
        impact: 'Over 50,000 downloads.',
        client_or_employer: 'FitLife Inc.',
      },
    ],
    processing_details: {
      processing_time_sec: 1.0,
      source_file: 'eva_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-01T12:00:00Z',
      cv_hash: 'hash-eva-005',
    },
  },

  {
    cv_id: 'cv-006',
    candidate_id: 'cand-006',
    cv_metadata: {
      cv_text: 'Experienced backend developer with expertise in Java and Spring Boot.',
      cv_language: 'en',
      summary: '7 years in backend development with a focus on scalable systems.',
    },
    candidate: {
      full_name: 'George King',
      first_name: 'George',
      last_name: 'King',
      email: 'george.king@example.com',
      phone: '+12021234567',
      birth_date: '1984-12-05',
      address: '101 Maple Road, New York, NY',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Software Engineering',
      experience_years: 7,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/georgeking',
      },
    ],
    education: [
      {
        degree: 'BSc Computer Science',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Computer Science',
        institution: 'New York University',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2006',
      },
    ],
    experience: [
      {
        company_name: 'TechSync',
        industry: 'Software',
        country: 'US',
        job_title: 'Backend Developer',
        start_date: '2015-01-01',
        end_date: '9999-12-31',
        description: 'Designed and maintained scalable backend systems.',
      },
    ],
    skills: [
      { name: 'Java', category: 'Backend' },
      { name: 'Spring Boot', category: 'Backend' },
    ],
    keywords: [{ keyword: 'Microservices', relevance_score: 0.87 }],
    certifications: [
      { name: 'Spring Professional Certification', provider: 'Pivotal', year: '2018' },
    ],
    projects: [
      {
        title: 'E-commerce Backend System',
        description: 'Developed the backend for an e-commerce platform.',
        role: 'Backend Developer',
        technologies_used: ['Java', 'Spring Boot', 'MySQL'],
        start_date: '2018-01-01',
        end_date: '2018-12-31',
        project_url: '',
        impact: 'Handled 1 million transactions daily.',
        client_or_employer: 'RetailX',
      },
    ],
    processing_details: {
      processing_time_sec: 1.1,
      source_file: 'george_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-03T10:00:00Z',
      cv_hash: 'hash-george-006',
    },
  },

  {
    cv_id: 'cv-007',
    candidate_id: 'cand-007',
    cv_metadata: {
      cv_text: 'Graphic Designer with a passion for branding and digital art.',
      cv_language: 'en',
      summary: '6 years of experience in graphic design and brand identity creation.',
    },
    candidate: {
      full_name: 'Hannah Lee',
      first_name: 'Hannah',
      last_name: 'Lee',
      email: 'hannah.lee@example.com',
      phone: '+442033445566',
      birth_date: '1989-02-14',
      address: '47 High Street, Manchester, UK',
      country_code: 'GB',
      country_name: 'United Kingdom',
      industry: 'Design',
      experience_years: 6,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/hannahlee',
      },
    ],
    education: [
      {
        degree: 'BA in Graphic Design',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Design',
        institution: 'Manchester Metropolitan University',
        institution_type: 'University',
        country: 'GB',
        education_framework: 'ISCED',
        graduation_year: '2014',
      },
    ],
    experience: [
      {
        company_name: 'DesignWorks Studio',
        industry: 'Design',
        country: 'GB',
        job_title: 'Graphic Designer',
        start_date: '2015-04-01',
        end_date: '9999-12-31',
        description: 'Created branding assets and marketing materials for clients.',
      },
    ],
    skills: [
      { name: 'Adobe Photoshop', category: 'Design Tools' },
      { name: 'Illustrator', category: 'Design Tools' },
    ],
    keywords: [{ keyword: 'Brand Identity', relevance_score: 0.89 }],
    certifications: [{ name: 'Adobe Certified Expert', provider: 'Adobe', year: '2017' }],
    projects: [
      {
        title: 'Branding for TechCorp',
        description: 'Developed the brand identity and logo.',
        role: 'Lead Designer',
        technologies_used: ['Photoshop', 'Illustrator'],
        start_date: '2019-05-01',
        end_date: '2020-05-01',
        project_url: '',
        impact: 'Increased brand recognition by 40%.',
        client_or_employer: 'TechCorp',
      },
    ],
    processing_details: {
      processing_time_sec: 1.0,
      source_file: 'hannah_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-05T11:00:00Z',
      cv_hash: 'hash-hannah-007',
    },
  },

  {
    cv_id: 'cv-008',
    candidate_id: 'cand-008',
    cv_metadata: {
      cv_text: 'Senior Frontend Developer with React and Angular expertise.',
      cv_language: 'en',
      summary: '8 years of experience in frontend development, particularly React and Angular.',
    },
    candidate: {
      full_name: 'Ian Walker',
      first_name: 'Ian',
      last_name: 'Walker',
      email: 'ian.walker@example.com',
      phone: '+61400335544',
      birth_date: '1986-11-29',
      address: '10 King Street, Sydney, Australia',
      country_code: 'AU',
      country_name: 'Australia',
      industry: 'Software Development',
      experience_years: 8,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/ianwalker',
      },
    ],
    education: [
      {
        degree: 'BSc Software Development',
        degree_Level: 'ISCED 6',
        degree_type: 'Bachelor',
        field_of_study: 'Software Development',
        institution: 'University of Sydney',
        institution_type: 'University',
        country: 'AU',
        education_framework: 'ISCED',
        graduation_year: '2008',
      },
    ],
    experience: [
      {
        company_name: 'WebCraft',
        industry: 'Software',
        country: 'AU',
        job_title: 'Senior Frontend Developer',
        start_date: '2014-03-01',
        end_date: '9999-12-31',
        description: 'Led frontend development of web applications using React and Angular.',
      },
    ],
    skills: [
      { name: 'React', category: 'Frontend' },
      { name: 'Angular', category: 'Frontend' },
    ],
    keywords: [{ keyword: 'Single Page Applications', relevance_score: 0.9 }],
    certifications: [{ name: 'React Developer Certificate', provider: 'Meta', year: '2019' }],
    projects: [
      {
        title: 'Real-Time Analytics Dashboard',
        description: 'Developed a dashboard for real-time data analytics.',
        role: 'Frontend Lead',
        technologies_used: ['React', 'Redux'],
        start_date: '2020-01-01',
        end_date: '2021-01-01',
        project_url: '',
        impact: 'Improved data processing speed by 30%.',
        client_or_employer: 'DataStream Ltd.',
      },
    ],
    processing_details: {
      processing_time_sec: 1.2,
      source_file: 'ian_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-07T14:00:00Z',
      cv_hash: 'hash-ian-008',
    },
  },

  {
    cv_id: 'cv-009',
    candidate_id: 'cand-009',
    cv_metadata: {
      cv_text: 'AI Researcher with expertise in natural language processing and computer vision.',
      cv_language: 'en',
      summary: '5 years of research experience in NLP and computer vision.',
    },
    candidate: {
      full_name: 'Julia Lee',
      first_name: 'Julia',
      last_name: 'Lee',
      email: 'julia.lee@example.com',
      phone: '+16175556666',
      birth_date: '1993-06-28',
      address: '4500 Oak Lane, Boston, MA',
      country_code: 'US',
      country_name: 'United States',
      industry: 'AI Research',
      experience_years: 5,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/julialee',
      },
    ],
    education: [
      {
        degree: 'PhD in Artificial Intelligence',
        degree_Level: 'ISCED 8',
        degree_type: 'PhD',
        field_of_study: 'AI Research',
        institution: 'Harvard University',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2020',
      },
    ],
    experience: [
      {
        company_name: 'AI Research Labs',
        industry: 'AI',
        country: 'US',
        job_title: 'AI Researcher',
        start_date: '2020-06-01',
        end_date: '9999-12-31',
        description: 'Conducted NLP and computer vision research for AI applications.',
      },
    ],
    skills: [
      { name: 'NLP', category: 'Machine Learning' },
      { name: 'OpenCV', category: 'Computer Vision' },
    ],
    keywords: [{ keyword: 'Deep Learning', relevance_score: 0.95 }],
    certifications: [{ name: 'Deep Learning Specialization', provider: 'Coursera', year: '2021' }],
    projects: [
      {
        title: 'Text Summarization System',
        description: 'Developed a model for summarizing long documents.',
        role: 'Lead Researcher',
        technologies_used: ['Python', 'TensorFlow', 'NLP'],
        start_date: '2021-03-01',
        end_date: '2022-06-01',
        project_url: '',
        impact: 'Reduced manual summarization time by 50%.',
        client_or_employer: 'AI Research Labs',
      },
    ],
    processing_details: {
      processing_time_sec: 1.4,
      source_file: 'julia_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-10T09:00:00Z',
      cv_hash: 'hash-julia-009',
    },
  },
  {
    cv_id: 'cv-010',
    candidate_id: 'cand-010',
    cv_metadata: {
      cv_text: 'AI Researcher with expertise in natural language processing and computer vision.',
      cv_language: 'en',
      summary: '5 years of research experience in NLP and computer vision.',
    },
    candidate: {
      full_name: 'omar ben chagra',
      first_name: 'omar',
      last_name: 'ben chagra',
      email: 'julia.lee@example.com',
      phone: '+16175556666',
      birth_date: '1993-06-28',
      address: '4500 Oak Lane, Boston, MA',
      country_code: 'US',
      country_name: 'United States',
      industry: 'AI Research',
      experience_years: 7,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/julialee',
      },
    ],
    education: [
      {
        degree: 'PhD in Artificial Intelligence',
        degree_Level: 'ISCED 8',
        degree_type: 'PhD',
        field_of_study: 'AI Research',
        institution: 'Harvard University',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2020',
      },
    ],
    experience: [
      {
        company_name: 'AI Research Labs',
        industry: 'AI',
        country: 'US',
        job_title: 'AI Researcher',
        start_date: '2020-06-01',
        end_date: '9999-12-31',
        description: 'Conducted NLP and computer vision research for AI applications.',
      },
    ],
    skills: [
      { name: 'NLP', category: 'Machine Learning' },
      { name: 'OpenCV', category: 'Computer Vision' },
    ],
    keywords: [{ keyword: 'Deep Learning', relevance_score: 0.95 }],
    certifications: [{ name: 'Deep Learning Specialization', provider: 'Coursera', year: '2021' }],
    projects: [
      {
        title: 'Text Summarization System',
        description: 'Developed a model for summarizing long documents.',
        role: 'Lead Researcher',
        technologies_used: ['Python', 'TensorFlow', 'NLP'],
        start_date: '2021-03-01',
        end_date: '2022-06-01',
        project_url: '',
        impact: 'Reduced manual summarization time by 50%.',
        client_or_employer: 'AI Research Labs',
      },
    ],
    processing_details: {
      processing_time_sec: 1.4,
      source_file: 'julia_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-04-10T09:00:00Z',
      cv_hash: 'hash-julia-009',
    },
  },
  {
    cv_id: 'cv-025',
    candidate_id: 'cand-025',
    cv_metadata: {
      cv_text:
        'Expert in cloud computing and system architecture with strong experience in building scalable solutions.',
      cv_language: 'en',
      summary: '6 years of hands-on experience in cloud architecture and DevOps.',
    },
    candidate: {
      full_name: 'samira bensaid',
      first_name: 'samira',
      last_name: 'bensaid',
      email: 'samira.bensaid@example.com',
      phone: '+16175558888',
      birth_date: '1989-02-22',
      address: '234 Maple Street, Denver, CO',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Cloud Computing',
      experience_years: 6,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/samirabensaid',
      },
    ],
    education: [
      {
        degree: "Master's in Cloud Computing",
        degree_Level: 'ISCED 7',
        degree_type: "Master's",
        field_of_study: 'Cloud Computing',
        institution: 'University of Colorado',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2016',
      },
    ],
    experience: [
      {
        company_name: 'CloudTech Solutions',
        industry: 'Cloud Computing',
        country: 'US',
        job_title: 'Cloud Architect',
        start_date: '2017-05-01',
        end_date: '9999-12-31',
        description: 'Designed and implemented scalable cloud solutions for enterprise clients.',
      },
    ],
    skills: [
      { name: 'AWS', category: 'Cloud Computing' },
      { name: 'Docker', category: 'DevOps' },
    ],
    keywords: [
      { keyword: 'Cloud Architecture', relevance_score: 0.92 },
      { keyword: 'Microservices', relevance_score: 0.89 },
    ],
    certifications: [
      { name: 'AWS Certified Solutions Architect', provider: 'Amazon', year: '2018' },
    ],
    projects: [
      {
        title: 'Cloud Migration Strategy',
        description: 'Led the migration of legacy systems to AWS cloud infrastructure.',
        role: 'Lead Architect',
        technologies_used: ['AWS', 'Terraform'],
        start_date: '2018-03-01',
        end_date: '2019-07-01',
        project_url: '',
        impact: 'Reduced costs by 30% while increasing system reliability.',
        client_or_employer: 'CloudTech Solutions',
      },
    ],
    processing_details: {
      processing_time_sec: 1.5,
      source_file: 'samira_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T09:00:00Z',
      cv_hash: 'hash-samira-025',
    },
  },
  {
    cv_id: 'cv-026',
    candidate_id: 'cand-026',
    cv_metadata: {
      cv_text: 'Data Engineer with expertise in ETL pipelines and data warehousing.',
      cv_language: 'en',
      summary: '7 years of experience in big data technologies and data management.',
    },
    candidate: {
      full_name: 'karim ouled',
      first_name: 'karim',
      last_name: 'ouled',
      email: 'karim.ouled@example.com',
      phone: '+16175559999',
      birth_date: '1988-08-10',
      address: '567 Pine Street, Miami, FL',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Data Engineering',
      experience_years: 7,
    },
    social_media: [
      {
        platform: 'GitHub',
        url: 'https://github.com/karimouled',
      },
    ],
    education: [
      {
        degree: "Bachelor's in Computer Science",
        degree_Level: 'ISCED 6',
        degree_type: "Bachelor's",
        field_of_study: 'Computer Science',
        institution: 'University of Miami',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2012',
      },
    ],
    experience: [
      {
        company_name: 'DataMinds Inc.',
        industry: 'Data Engineering',
        country: 'US',
        job_title: 'Data Engineer',
        start_date: '2015-06-01',
        end_date: '9999-12-31',
        description: 'Built and maintained ETL pipelines for large-scale data processing.',
      },
    ],
    skills: [
      { name: 'ETL', category: 'Data Engineering' },
      { name: 'Hadoop', category: 'Big Data' },
    ],
    keywords: [
      { keyword: 'Data Warehousing', relevance_score: 0.91 },
      { keyword: 'Spark', relevance_score: 0.88 },
    ],
    certifications: [{ name: 'Certified Data Engineer', provider: 'Data Academy', year: '2019' }],
    projects: [
      {
        title: 'Real-Time Data Processing System',
        description: 'Developed a real-time data processing system using Apache Kafka and Spark.',
        role: 'Lead Data Engineer',
        technologies_used: ['Apache Kafka', 'Spark', 'Python'],
        start_date: '2020-01-01',
        end_date: '2021-05-01',
        project_url: '',
        impact: 'Enabled real-time insights from big data sources.',
        client_or_employer: 'DataMinds Inc.',
      },
    ],
    processing_details: {
      processing_time_sec: 1.3,
      source_file: 'karim_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T09:30:00Z',
      cv_hash: 'hash-karim-026',
    },
  },
  {
    cv_id: 'cv-027',
    candidate_id: 'cand-027',
    cv_metadata: {
      cv_text:
        'Experienced software engineer with a focus on full-stack web development and scalable applications.',
      cv_language: 'en',
      summary:
        '5 years of experience in building modern web applications with React, Node.js, and MongoDB.',
    },
    candidate: {
      full_name: 'nora zied',
      first_name: 'nora',
      last_name: 'zied',
      email: 'nora.zied@example.com',
      phone: '+16175554444',
      birth_date: '1994-01-11',
      address: '890 Birch Street, Austin, TX',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Software Development',
      experience_years: 5,
    },
    social_media: [
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/norazied',
      },
    ],
    education: [
      {
        degree: "Bachelor's in Computer Engineering",
        degree_Level: 'ISCED 6',
        degree_type: "Bachelor's",
        field_of_study: 'Computer Engineering',
        institution: 'University of Texas',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2017',
      },
    ],
    experience: [
      {
        company_name: 'TechSolutions',
        industry: 'Software Development',
        country: 'US',
        job_title: 'Full-Stack Developer',
        start_date: '2017-08-01',
        end_date: '9999-12-31',
        description: 'Developed and maintained full-stack applications for e-commerce platforms.',
      },
    ],
    skills: [
      { name: 'React', category: 'Frontend Development' },
      { name: 'Node.js', category: 'Backend Development' },
      { name: 'MongoDB', category: 'Database' },
    ],
    keywords: [
      { keyword: 'JavaScript', relevance_score: 0.95 },
      { keyword: 'React.js', relevance_score: 0.94 },
    ],
    certifications: [
      { name: 'Full-Stack Web Development', provider: 'FreeCodeCamp', year: '2018' },
    ],
    projects: [
      {
        title: 'E-commerce Platform',
        description: 'Built an end-to-end e-commerce platform with payment gateway integration.',
        role: 'Lead Developer',
        technologies_used: ['React', 'Node.js', 'MongoDB'],
        start_date: '2018-04-01',
        end_date: '2019-08-01',
        project_url: '',
        impact: 'Increased user engagement by 40% due to improved UI and performance.',
        client_or_employer: 'TechSolutions',
      },
    ],
    processing_details: {
      processing_time_sec: 1.6,
      source_file: 'nora_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T10:00:00Z',
      cv_hash: 'hash-nora-027',
    },
  },

  {
    cv_id: 'cv-028',
    candidate_id: 'cand-028',
    cv_metadata: {
      cv_text:
        'Skilled backend developer with expertise in Python, Django, and cloud infrastructure.',
      cv_language: 'en',
      summary:
        '6 years of experience in building backend systems with a focus on scalability and performance.',
    },
    candidate: {
      full_name: 'ahmed ahmed',
      first_name: 'ahmed',
      last_name: 'ahmed',
      email: 'ahmed@example.com',
      phone: '+16175553333',
      birth_date: '1991-05-12',
      address: '123 Elm Street, Seattle, WA',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Software Development',
      experience_years: 6,
    },
    social_media: [
      {
        platform: 'GitHub',
        url: 'https://github.com/ahmedahmed',
      },
      {
        platform: 'Twitter',
        url: 'https://twitter.com/ahmedahmed',
      },
    ],
    education: [
      {
        degree: "Bachelor's in Software Engineering",
        degree_Level: 'ISCED 6',
        degree_type: "Bachelor's",
        field_of_study: 'Software Engineering',
        institution: 'University of Washington',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2014',
      },
    ],
    experience: [
      {
        company_name: 'CloudWorks',
        industry: 'Software Development',
        country: 'US',
        job_title: 'Backend Developer',
        start_date: '2015-04-01',
        end_date: '9999-12-31',
        description: 'Developed backend systems for cloud-based applications and services.',
      },
    ],
    skills: [
      { name: 'Python', category: 'Programming' },
      { name: 'Django', category: 'Web Development' },
    ],
    keywords: [
      { keyword: 'Cloud Infrastructure', relevance_score: 0.89 },
      { keyword: 'API Development', relevance_score: 0.91 },
    ],
    certifications: [{ name: 'AWS Certified Developer', provider: 'Amazon', year: '2019' }],
    projects: [
      {
        title: 'Microservices Architecture',
        description:
          'Designed a microservices architecture to improve scalability and maintainability.',
        role: 'Lead Backend Developer',
        technologies_used: ['Python', 'Django', 'AWS'],
        start_date: '2019-05-01',
        end_date: '2020-11-01',
        project_url: '',
        impact: 'Improved system uptime by 99.9% and reduced deployment time.',
        client_or_employer: 'CloudWorks',
      },
    ],
    processing_details: {
      processing_time_sec: 1.4,
      source_file: 'ahmed_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T10:30:00Z',
      cv_hash: 'hash-ahmed-028',
    },
  },
  {
    cv_id: 'cv-029',
    candidate_id: 'cand-029',
    cv_metadata: {
      cv_text:
        'UI/UX Designer with a focus on creating user-centered designs for web and mobile applications.',
      cv_language: 'en',
      summary: '5 years of experience in UI/UX design, prototyping, and user testing.',
    },
    candidate: {
      full_name: 'david dupont',
      first_name: 'david',
      last_name: 'dupont',
      email: 'david@example.com',
      phone: '+16175554455',
      birth_date: '1990-07-20',
      address: '456 Cedar Road, Los Angeles, CA',
      country_code: 'US',
      country_name: 'United States',
      industry: 'Design',
      experience_years: 5,
    },
    social_media: [
      {
        platform: 'Instagram',
        url: 'https://www.instagram.com/davido_designs',
      },
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/in/daviddupont',
      },
    ],
    education: [
      {
        degree: "Bachelor's in Graphic Design",
        degree_Level: 'ISCED 6',
        degree_type: "Bachelor's",
        field_of_study: 'Graphic Design',
        institution: 'California Institute of the Arts',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2015',
      },
    ],
    experience: [
      {
        company_name: 'DesignHub',
        industry: 'Design',
        country: 'US',
        job_title: 'UI/UX Designer',
        start_date: '2016-01-01',
        end_date: '9999-12-31',
        description: 'Designed UI/UX for mobile and web applications to improve user experience.',
      },
    ],
    skills: [
      { name: 'Adobe XD', category: 'Design' },
      { name: 'Figma', category: 'Design' },
      { name: 'User Research', category: 'Research' },
    ],
    keywords: [
      { keyword: 'UI Design', relevance_score: 0.92 },
      { keyword: 'Prototyping', relevance_score: 0.88 },
    ],
    certifications: [
      { name: 'Certified UX Designer', provider: 'UX Design Institute', year: '2018' },
    ],
    projects: [
      {
        title: 'Mobile App Redesign',
        description:
          'Led the redesign of a popular mobile app to improve usability and user engagement.',
        role: 'Lead UI/UX Designer',
        technologies_used: ['Adobe XD', 'Figma'],
        start_date: '2019-06-01',
        end_date: '2020-08-01',
        project_url: '',
        impact: 'Increased app downloads by 25% due to improved design and functionality.',
        client_or_employer: 'DesignHub',
      },
    ],
    processing_details: {
      processing_time_sec: 1.3,
      source_file: 'david_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T11:00:00Z',
      cv_hash: 'hash-david-029',
    },
  },
  {
    cv_id: 'cv-030',
    candidate_id: 'cand-030',
    cv_metadata: {
      cv_text:
        'DevOps Engineer with strong experience in automation, continuous integration, and containerization.',
      cv_language: 'en',
      summary:
        '7 years of experience building and maintaining CI/CD pipelines and managing cloud infrastructure.',
    },
    candidate: {
      full_name: 'youssef salem',
      first_name: 'youssef',
      last_name: 'salem',
      email: 'youssef.salem@example.com',
      phone: '+16175551111',
      birth_date: '1987-09-15',
      address: '789 Maple Avenue, Chicago, IL',
      country_code: 'US',
      country_name: 'United States',
      industry: 'DevOps',
      experience_years: 7,
    },
    social_media: [
      {
        platform: 'Jdida',
        url: 'https://www.linkedin.com/in/youssefsalem',
      },
    ],
    education: [
      {
        degree: "Bachelor's in Information Technology",
        degree_Level: 'ISCED 6',
        degree_type: "Bachelor's",
        field_of_study: 'Information Technology',
        institution: 'University of Illinois',
        institution_type: 'University',
        country: 'US',
        education_framework: 'ISCED',
        graduation_year: '2012',
      },
    ],
    experience: [
      {
        company_name: 'CloudOps Solutions',
        industry: 'DevOps',
        country: 'US',
        job_title: 'DevOps Engineer',
        start_date: '2014-03-01',
        end_date: '9999-12-31',
        description: 'Managed CI/CD pipelines and automated infrastructure provisioning on AWS.',
      },
    ],
    skills: [
      { name: 'AWS', category: 'Cloud Computing' },
      { name: 'Docker', category: 'Containerization' },
      { name: 'Jenkins', category: 'CI/CD' },
    ],
    keywords: [
      { keyword: 'Automation', relevance_score: 0.93 },
      { keyword: 'CI/CD', relevance_score: 0.9 },
    ],
    certifications: [{ name: 'AWS Certified DevOps Engineer', provider: 'Amazon', year: '2017' }],
    projects: [
      {
        title: 'Automated Cloud Infrastructure',
        description:
          'Implemented automated cloud infrastructure provisioning using Terraform and AWS.',
        role: 'DevOps Engineer',
        technologies_used: ['Terraform', 'AWS', 'Jenkins'],
        start_date: '2018-07-01',
        end_date: '2019-10-01',
        project_url: '',
        impact: 'Reduced manual provisioning time by 75%.',
        client_or_employer: 'CloudOps Solutions',
      },
    ],
    processing_details: {
      processing_time_sec: 1.2,
      source_file: 'youssef_cv.pdf',
      source_format: 'application/pdf',
      upload_datetime: '2025-05-10T11:30:00Z',
      cv_hash: 'hash-youssef-030',
    },
  },

  // Add more as needed...
];
