export const mockCandidates = [
  { id: '1', full_name: 'Facundo Kent', location_country: 'Argentina' },
  { id: '2', full_name: 'Jane Doe', location_country: 'France' },
  { id: '3', full_name: 'Amir Zanned', location_country: 'Tunisia' },
  { id: '4', full_name: 'Omar Chagra', location_country: 'Tunisia' },
  { id: '5', full_name: 'John Smith', location_country: 'United States' },
  { id: '6', full_name: 'Maria Silva', location_country: 'Brazil' },
  { id: '7', full_name: 'Ali Hassan', location_country: 'Egypt' },
  { id: '8', full_name: 'Tom Lee', location_country: 'South Korea' },
  { id: '9', full_name: 'Emily Chen', location_country: 'China' },
  { id: '10', full_name: 'Sarah Connor', location_country: 'United Kingdom' },
  { id: '11', full_name: 'Ahmed Ben Ali', location_country: 'Tunisia' },
  { id: '12', full_name: 'Anna Schmidt', location_country: 'Germany' },
  { id: '13', full_name: 'Ivan Petrov', location_country: 'Russia' },
  { id: '14', full_name: 'Carlos Gomez', location_country: 'Mexico' },
  { id: '15', full_name: 'Yuki Sato', location_country: 'Japan' },
  { id: '16', full_name: 'Fatima Zahra', location_country: 'Morocco' },
  { id: '17', full_name: 'David Miller', location_country: 'Canada' },
  { id: '18', full_name: 'Isabelle Dubois', location_country: 'France' },
  { id: '19', full_name: 'Santiago Lopez', location_country: 'Argentina' },
  { id: '20', full_name: 'James Brown', location_country: 'United States' },
  { id: '21', full_name: 'Linda Park', location_country: 'South Korea' },
  { id: '22', full_name: 'Mohamed Salah', location_country: 'Egypt' },
  { id: '23', full_name: 'Natalie Johnson', location_country: 'United States' },
  { id: '24', full_name: 'Lucas Moreau', location_country: 'France' },
  { id: '25', full_name: 'Chen Wei', location_country: 'China' },
  { id: '26', full_name: 'Gabriel Torres', location_country: 'Brazil' },
  { id: '27', full_name: 'Sophia Müller', location_country: 'Germany' },
  { id: '28', full_name: 'Hiro Tanaka', location_country: 'Japan' },
  { id: '29', full_name: 'Nadia Ahmed', location_country: 'Morocco' },
  { id: '30', full_name: 'Ethan Walker', location_country: 'Canada' },
  { id: '31', full_name: 'Clara Rossi', location_country: 'Italy' },
  { id: '32', full_name: 'Mateo Alvarez', location_country: 'Mexico' },
  { id: '33', full_name: 'Olga Ivanova', location_country: 'Russia' },
  { id: '34', full_name: 'James Wilson', location_country: 'United Kingdom' },
  { id: '35', full_name: 'Liam Smith', location_country: 'Australia' },
  { id: '36', full_name: 'Amina Yusuf', location_country: 'Nigeria' },
  { id: '37', full_name: 'Pedro Silva', location_country: 'Portugal' },
  { id: '38', full_name: 'Isabel Garcia', location_country: 'Spain' },
  { id: '39', full_name: 'Jonas Lindberg', location_country: 'Sweden' },
  { id: '40', full_name: 'Anna Novak', location_country: 'Poland' },
  { id: '41', full_name: 'Carlos Santana', location_country: 'Argentina' },
  { id: '42', full_name: 'Mina Hassan', location_country: 'Egypt' },
  { id: '43', full_name: 'Fatima Khan', location_country: 'Pakistan' },
  { id: '44', full_name: 'David Johnson', location_country: 'United States' },
  { id: '45', full_name: 'Sophie Laurent', location_country: 'France' },
  { id: '46', full_name: 'Mark Lee', location_country: 'South Korea' },
  { id: '47', full_name: 'Hana Yamamoto', location_country: 'Japan' },
  { id: '48', full_name: 'Elena Petrova', location_country: 'Russia' },
  { id: '49', full_name: 'Tom Brown', location_country: 'United Kingdom' },
  { id: '50', full_name: 'Marta Rossi', location_country: 'Italy' },
  { id: '51', full_name: 'Carlos Mendez', location_country: 'Mexico' },
  { id: '52', full_name: 'Julia Fischer', location_country: 'Germany' },
  { id: '53', full_name: 'Wei Zhang', location_country: 'China' },
  { id: '54', full_name: 'Alice Johnson', location_country: 'Canada' },
  { id: '55', full_name: 'Mohammed Ali', location_country: 'United Arab Emirates' },
  { id: '56', full_name: 'Laura Martinez', location_country: 'Spain' },
  { id: '57', full_name: 'Henrik Svensson', location_country: 'Sweden' },
  { id: '58', full_name: 'Anja Schmidt', location_country: 'Germany' },
  { id: '59', full_name: 'Kwaku Mensah', location_country: 'Ghana' },
  { id: '60', full_name: 'Olivia Taylor', location_country: 'Australia' },
  { id: '61', full_name: 'Daniel Silva', location_country: 'Portugal' },
  { id: '62', full_name: 'Sophia Lee', location_country: 'South Korea' },
  { id: '63', full_name: 'Mohammed Yusuf', location_country: 'Morocco' },
  { id: '64', full_name: 'Peter Novak', location_country: 'Poland' },
  { id: '65', full_name: 'Laura Brown', location_country: 'United States' },
  { id: '66', full_name: 'Ahmed Saeed', location_country: 'Egypt' },
  { id: '67', full_name: 'Isabella Costa', location_country: 'Brazil' },
  { id: '68', full_name: 'James Wilson', location_country: 'United Kingdom' },
  { id: '69', full_name: 'Natalia Kowalska', location_country: 'Poland' },
  { id: '70', full_name: 'David Miller', location_country: 'Canada' },
  { id: '71', full_name: 'Lucas Silva', location_country: 'Portugal' },
  { id: '72', full_name: 'Anna Müller', location_country: 'Germany' },
  { id: '73', full_name: 'Mohamed El-Sayed', location_country: 'Egypt' },
  { id: '74', full_name: 'Laura Dupont', location_country: 'France' },
  { id: '75', full_name: 'Omar Chagra', location_country: 'Tunisia' },
  { id: '76', full_name: 'Megan Smith', location_country: 'United States' },
  { id: '77', full_name: 'Lucas Moreau', location_country: 'France' },
  { id: '78', full_name: 'Aya Tanaka', location_country: 'Japan' },
  { id: '79', full_name: 'Ali Hassan', location_country: 'Egypt' },
  { id: '80', full_name: 'Emily Chen', location_country: 'China' },
  { id: '81', full_name: 'Anna Schmidt', location_country: 'Germany' },
  { id: '82', full_name: 'James Brown', location_country: 'United States' },
  { id: '83', full_name: 'Isabelle Dubois', location_country: 'France' },
  { id: '84', full_name: 'Pedro Silva', location_country: 'Portugal' },
  { id: '85', full_name: 'Maria Lopez', location_country: 'Mexico' },
  { id: '86', full_name: 'John Smith', location_country: 'United States' },
  { id: '87', full_name: 'Sofia Garcia', location_country: 'Spain' },
  { id: '88', full_name: 'Daniel Kim', location_country: 'South Korea' },
  { id: '89', full_name: 'Fatima Zahra', location_country: 'Morocco' },
  { id: '90', full_name: 'Mateusz Kowalski', location_country: 'Poland' },
  { id: '91', full_name: 'Mohammed Ali', location_country: 'United Arab Emirates' },
  { id: '92', full_name: 'David Miller', location_country: 'Canada' },
  { id: '93', full_name: 'Emily Clark', location_country: 'United Kingdom' },
  { id: '94', full_name: 'Lucas Martinez', location_country: 'Mexico' },
  { id: '95', full_name: 'Sara Ahmed', location_country: 'Egypt' },
  { id: '96', full_name: 'Isabella Rossi', location_country: 'Italy' },
  { id: '97', full_name: 'John Doe', location_country: 'United States' },
  { id: '98', full_name: 'Maria Silva', location_country: 'Brazil' },
  { id: '99', full_name: 'Carlos Gomez', location_country: 'Argentina' },
  { id: '100', full_name: 'Anna Novak', location_country: 'Poland' },
  { id: '101', full_name: 'Omar Haddad', location_country: 'Tunisia' },
  { id: '102', full_name: 'Lina Bouchard', location_country: 'France' },
  { id: '103', full_name: 'Daniel Kim', location_country: 'South Korea' },
  { id: '104', full_name: 'Aisha Khan', location_country: 'Pakistan' },
  { id: '105', full_name: 'Carlos Mendoza', location_country: 'Mexico' },
  { id: '106', full_name: 'Yasmine El Fassi', location_country: 'Morocco' },
  { id: '107', full_name: 'Hiroshi Sato', location_country: 'Japan' },
  { id: '108', full_name: 'Sophia Fischer', location_country: 'Germany' },
  { id: '109', full_name: 'Ahmed Hassan', location_country: 'Egypt' },
  { id: '110', full_name: 'Maria Ivanova', location_country: 'Russia' },
  { id: '111', full_name: 'Emily Smith', location_country: 'United States' },
  { id: '112', full_name: 'Chen Ming', location_country: 'China' },
  { id: '113', full_name: 'Santiago Ruiz', location_country: 'Argentina' },
  { id: '114', full_name: 'Fatima Zahra', location_country: 'Morocco' },
  { id: '115', full_name: 'Tomoko Yamashita', location_country: 'Japan' },
  { id: '116', full_name: 'Ivan Popov', location_country: 'Russia' },
  { id: '117', full_name: 'Laura Müller', location_country: 'Germany' },
  { id: '118', full_name: 'Mark Johnson', location_country: 'United Kingdom' },
  { id: '119', full_name: 'Isabel Gonzalez', location_country: 'Spain' },
  { id: '120', full_name: 'Ali Ben Youssef', location_country: 'Tunisia' },
  { id: '121', full_name: 'Nadia Ali', location_country: 'Pakistan' },
  { id: '122', full_name: 'Lucas Moreau', location_country: 'France' },
  { id: '123', full_name: 'Anna Nowak', location_country: 'Poland' },
  { id: '124', full_name: 'Mikhail Smirnov', location_country: 'Russia' },
  { id: '125', full_name: 'Wei Li', location_country: 'China' },
  { id: '126', full_name: 'David Brown', location_country: 'United States' },
  { id: '127', full_name: 'Clara Schmidt', location_country: 'Germany' },
  { id: '128', full_name: 'Amira Nasser', location_country: 'Egypt' },
  { id: '129', full_name: 'Pedro Alves', location_country: 'Brazil' },
  { id: '130', full_name: 'Sarah Miller', location_country: 'Canada' },
  { id: '131', full_name: 'Yusuf Elamin', location_country: 'Sudan' },
  { id: '132', full_name: 'Emily Taylor', location_country: 'Australia' },
  { id: '133', full_name: 'Anna Kowalska', location_country: 'Poland' },
  { id: '134', full_name: 'Lucas Silva', location_country: 'Portugal' },
  { id: '135', full_name: 'Ahmed Omar', location_country: 'United Arab Emirates' },
  { id: '136', full_name: 'Nora Hassan', location_country: 'Egypt' },
  { id: '137', full_name: 'Marcos Santos', location_country: 'Brazil' },
  { id: '138', full_name: 'Emily Chen', location_country: 'China' },
  { id: '139', full_name: 'Sophia Laurent', location_country: 'France' },
  { id: '140', full_name: 'Olga Petrova', location_country: 'Russia' },
  { id: '141', full_name: 'Mohamed Abdelrahman', location_country: 'Egypt' },
  { id: '142', full_name: 'James Wilson', location_country: 'United Kingdom' },
  { id: '143', full_name: 'Nikita Ivanov', location_country: 'Russia' },
  { id: '144', full_name: 'Zainab Ali', location_country: 'Pakistan' },
  { id: '145', full_name: 'Chen Yu', location_country: 'China' },
  { id: '146', full_name: 'Sebastian Cruz', location_country: 'Argentina' },
  { id: '147', full_name: 'Marta Rossi', location_country: 'Italy' },
  { id: '148', full_name: 'Ismael Toumi', location_country: 'Tunisia' },
  { id: '149', full_name: 'Julie Tremblay', location_country: 'Canada' },
  { id: '150', full_name: 'Aiko Tanaka', location_country: 'Japan' },
  { id: '151', full_name: 'Paul Dubois', location_country: 'France' },
  { id: '152', full_name: 'David Park', location_country: 'South Korea' },
  { id: '153', full_name: 'Lucia Morales', location_country: 'Mexico' },
  { id: '154', full_name: 'Khalid Rahman', location_country: 'United Arab Emirates' },
  { id: '155', full_name: 'Daniela Sousa', location_country: 'Portugal' },
  { id: '156', full_name: 'Sandra Meyer', location_country: 'Germany' },
  { id: '157', full_name: 'Joshua Lee', location_country: 'United States' },
  { id: '158', full_name: 'Fatou Ndiaye', location_country: 'Senegal' },
  { id: '159', full_name: 'Noah Becker', location_country: 'Germany' },
  { id: '160', full_name: 'Luisa Fernandez', location_country: 'Spain' },
  { id: '161', full_name: 'Aliya Malik', location_country: 'Pakistan' },
  { id: '162', full_name: 'Kim Soo-Min', location_country: 'South Korea' },
  { id: '163', full_name: 'Oussama Mahfoudh', location_country: 'Tunisia' },
  { id: '164', full_name: 'Emma Wilson', location_country: 'Canada' },
  { id: '165', full_name: 'Mateusz Zielinski', location_country: 'Poland' },
  { id: '166', full_name: 'Sofia Rojas', location_country: 'Mexico' },
  { id: '167', full_name: 'Mahmoud Farag', location_country: 'Egypt' },
  { id: '168', full_name: 'Isabella Rossi', location_country: 'Italy' },
  { id: '169', full_name: 'Yasmine Bouazizi', location_country: 'Tunisia' },
  { id: '170', full_name: 'Ivan Morozov', location_country: 'Russia' },
  { id: '171', full_name: 'Emily Martin', location_country: 'United States' },
  { id: '172', full_name: 'Laura Nowak', location_country: 'Poland' },
  { id: '173', full_name: 'João Pereira', location_country: 'Brazil' },
  { id: '174', full_name: 'Mohammed El Amine', location_country: 'Morocco' },
  { id: '175', full_name: 'Alice Dubois', location_country: 'France' },
  { id: '176', full_name: 'Emma Novak', location_country: 'Poland' },
  { id: '177', full_name: 'Hassan Kamal', location_country: 'Egypt' },
  { id: '178', full_name: 'Liam White', location_country: 'United Kingdom' },
  { id: '179', full_name: 'Lucia Greco', location_country: 'Italy' },
  { id: '180', full_name: 'Karim Ben Amar', location_country: 'Tunisia' },
  { id: '181', full_name: 'Mohammed Bilal', location_country: 'Pakistan' },
  { id: '182', full_name: 'Noura Elhaj', location_country: 'Morocco' },
  { id: '183', full_name: 'George Carter', location_country: 'United States' },
  { id: '184', full_name: 'Ana Lopez', location_country: 'Mexico' },
  { id: '185', full_name: 'Ahmed Nabil', location_country: 'Egypt' },
  { id: '186', full_name: 'Yuki Nakamura', location_country: 'Japan' },
  { id: '187', full_name: 'Maria Costa', location_country: 'Portugal' },
  { id: '188', full_name: 'Elias Haddad', location_country: 'Lebanon' },
  { id: '189', full_name: 'Gabriel Lima', location_country: 'Brazil' },
  { id: '190', full_name: 'Sara Hassan', location_country: 'United Arab Emirates' },
  { id: '191', full_name: 'Mariam Daho', location_country: 'Algeria' },
  { id: '192', full_name: 'Emma Scott', location_country: 'Australia' },
  { id: '193', full_name: 'Viktor Volkov', location_country: 'Russia' },
  { id: '194', full_name: 'Sasha Ivanova', location_country: 'Russia' },
  { id: '195', full_name: 'Mehdi Boukhris', location_country: 'Tunisia' },
  { id: '196', full_name: 'Julia Nowak', location_country: 'Poland' },
  { id: '197', full_name: 'Chen Xi', location_country: 'China' },
  { id: '198', full_name: 'James Carter', location_country: 'United States' },
  { id: '199', full_name: 'Marie Dubois', location_country: 'France' },
  { id: '200', full_name: 'Ali Chahed', location_country: 'Tunisia' },
];

// Recalculate countryCounts based on the new list:
export const countryCounts = mockCandidates.reduce((acc, c) => {
  const country = c.location_country?.toLowerCase();
  acc[country] = (acc[country] || 0) + 1;
  return acc;
}, {});
